import type { KnowledgeItem, ProcessingJob } from "./types";

/* ─── Knowledge Items ─────────────────────────────────────────────── */
export const KNOWLEDGE_ITEMS: KnowledgeItem[] = [
  {
    id: "kb-001",
    title: "Neural Core Architecture Overview",
    fileType: "pdf",
    size: "1.2 MB",
    status: "indexed",
    uploadDate: "2026-07-20",
    source: "internal",
    tags: ["architecture", "core", "design"],
    chunks: 48,
    preview: "Comprehensive overview of the Neural Core system architecture, API gateway design, and component interactions.",
  },
  {
    id: "kb-002",
    title: "Next.js 15 App Router Docs",
    fileType: "md",
    size: "842 KB",
    status: "indexed",
    uploadDate: "2026-07-21",
    source: "nextjs.org",
    tags: ["next.js", "frontend", "docs"],
    chunks: 132,
    preview: "Official Next.js 15 documentation covering App Router, Server Components, and data fetching patterns.",
  },
  {
    id: "kb-003",
    title: "User Interview Notes — July 2026",
    fileType: "docx",
    size: "256 KB",
    status: "indexed",
    uploadDate: "2026-07-18",
    source: "notion-export",
    tags: ["research", "users", "product"],
    chunks: 22,
    preview: "Qualitative research notes from 12 user interviews covering pain points, feature requests, and workflow habits.",
  },
  {
    id: "kb-004",
    title: "FastAPI Backend Design Spec",
    fileType: "pdf",
    size: "3.1 MB",
    status: "processing",
    uploadDate: "2026-07-22",
    source: "internal",
    tags: ["backend", "api", "spec"],
    chunks: undefined,
    preview: "API design specification for the Neural Core backend services including endpoint contracts and auth flows.",
  },
  {
    id: "kb-005",
    title: "Product Roadmap Screenshot",
    fileType: "image",
    size: "4.7 MB",
    status: "indexed",
    uploadDate: "2026-07-19",
    source: "figma-export",
    tags: ["roadmap", "planning"],
    chunks: 8,
    preview: "Visual roadmap exported from Figma showing Q3-Q4 2026 feature milestones.",
  },
  {
    id: "kb-006",
    title: "LLM Evaluation Benchmark Results",
    fileType: "txt",
    size: "128 KB",
    status: "failed",
    uploadDate: "2026-07-22",
    source: "ci-pipeline",
    tags: ["llm", "benchmarks", "eval"],
    chunks: undefined,
    preview: "Automated benchmark results comparing model performance across accuracy, latency, and cost dimensions.",
  },
];

/* ─── Processing Queue ────────────────────────────────────────────── */
export const PROCESSING_JOBS: ProcessingJob[] = [
  {
    id: "job-001",
    fileName: "FastAPI Backend Design Spec.pdf",
    fileType: "pdf",
    stage: "chunking",
    progress: 42,
    size: "3.1 MB",
    startedAt: "Just now",
  },
  {
    id: "job-002",
    fileName: "TypeScript Handbook 5.0.md",
    fileType: "md",
    stage: "embedding",
    progress: 78,
    size: "620 KB",
    startedAt: "2 min ago",
  },
  {
    id: "job-003",
    fileName: "System Design Notes.docx",
    fileType: "docx",
    stage: "uploading",
    progress: 15,
    size: "1.8 MB",
    startedAt: "Just now",
  },
];
